version: '3.4'

services:
  Plant-Backend:
    image: plant
    build:
      context: back-end/Plant-Project-Backend
      dockerfile: Plant-Project-Backend/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - plantnetwork

networks:
  plantnetwork:
    driver: bridge