version: '3.4'
 
services:
  flyway:
      image: flyway/flyway
      container_name: PlantFlyway
      command: -url=jdbc:mysql://host.docker.internal:3307/PlantDB -user=user -password=root -connectRetries=60 migrate
      volumes:
        - .:/flyway/sql/migrations
      depends_on:
        - db

  db:
    image: mysql:latest
    container_name: PlantDB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'PlantDB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PlantPhpmyadmindb
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8080:80