name: .NET Core CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.gitignore"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.gitignore"

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ./back-end
      strategy:
        matrix:
          configuration: [Debug, Release]

      runs-on: windows-latest

      env:
        Solution_Name: Plant-Project-Backend.sln
        Test_Project_Path: Plant-Project-Backend.Plant-Project-Tests.csproj

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.100

        - name: Install dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build

        - name: Execute unit tests
          run: dotnet test
