name: .NET Core CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.gitignore"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.gitignore"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Plant-Project-Backend.sln # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: Plant-Project-Backend.Plant-Project-Tests.csproj # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Install dependencies
        run: dotnet restore Plant-Project-Backend

      - name: Build
        run: dotnet build Plant-Project-Backend

      - name: Execute unit tests
        run: dotnet test Plant-Project-Backend
