name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.gitignore"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.gitignore"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./front-end/Plant-Project-Frontend
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: install Node for CI
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
    
    - name: Test
      run: npm test
